services:
  postgres:
    image: postgres:18-alpine
    container_name: lego-postgres_dev
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - data

  postgres-test:
    image: postgres:18-alpine
    container_name: lego-postgres_test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lego_test
    networks:
      - data

  adminer:
    container_name: lego-adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - postgres
      - postgres-test
    networks:
      - data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: lego-mqtt
    ports:
      - $QUEUE_PORT:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - data

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: lego-mqtt-explorer
    depends_on:
      - mqtt
    ports:
      - "4000:4000"
    environment:
      HTTP_PORT: 4000
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
    networks:
      - data

volumes:
  postgres_dev_data:
  postgres_test_data:

networks:
  data: